[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dorsal-whisper"
version = "0.5.0"
description = "Dorsal model: dorsal-whisper"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dorsalhub>=0.9.5",
    "faster-whisper>=1.2.1",
    "protobuf>=7.35.1",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "mypy"
]

[project.entry-points."dorsal.models"]
dorsal_whisper = "dorsal_whisper"

[tool.hatch.build.targets.wheel]
packages = ["dorsal_whisper"]

[tool.hatch.build.targets.wheel.force-include]
"model_config.toml" = "dorsal_whisper/model_config.toml"

[tool.uv.sources]
dorsalhub = { path = "../dorsal/dist/dorsalhub-0.9.5-py3-none-any.whl" }